steps:
  # Install
  - name: "gcr.io/cloud-builders/yarn"
    entrypoint: "yarn"
    args: ["install", "--ignore-engines"]

  # Build
  - name: "gcr.io/cloud-builders/yarn"
    entrypoint: "yarn"
    args: ["build", "--ignore-engines"]

  # Ls
  - name: "gcr.io/cloud-builders/gcloud:latest"
    entrypoint: "ls"

  # Deploy
  - name: "gcr.io/firebase-hosting-286313/firebase"
    args: ["deploy"]
