steps:
  # Install
  - name: "gcr.io/cloud-builders/yarn"
    args: ["install"]

  # Build
  - name: "gcr.io/cloud-builders/yarn"
    args: ["build"]

  # Deploy
  - name: gcr.io/firebase-hosting-286313/firebase
    args: ["deploy"]
